### ISSUE TITLE
ERROR Error: Portals cannot be used without TuiPortalHostComponent

### ISSUE THREAD

**Issue by Kwab-Amp** [hakimio/ngx-ui-tour#57]
I keep running into this error with the `TourUIDropdown`.
Any help with what's wrong

**Comment by hakimio** [comment]
Can you share some code reproducing the issue?

**Comment by hakimio** [comment]
Do you still get this error if you use taiga-ui v2.32 ?

**Comment by Kwab-Amp** [comment]
Here's the link to my app files:

- [AppModule](https://github.com/Kwab-Amp/sample-angular-tour-app/blob/master/src/app/app.module.ts)
- [AppComponent](https://github.com/Kwab-Amp/sample-angular-tour-app/blob/master/src/app/app.component.ts)
- [Template](https://github.com/Kwab-Amp/sample-angular-tour-app/blob/master/src/app/app.component.html)

**Comment by hakimio** [comment]
Ok, actually this is not an issue with this library. The issue is that you haven't followed "Taiga UI" "Getting Started" guide. [Step 3](https://taiga-ui.dev/getting-started#root) of the guide states that you have to use `tui-root` component.
If you add `tui-root` and "Taiga UI" [styles](https://taiga-ui.dev/getting-started#styles), everything works as expected.
